CREATE TABLE TRAININGS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    DATE DATE,
    HOURS VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    PROVINCE VARCHAR(255),
    COST VARCHAR(255),
    RESTRICTION VARCHAR(255)
);