CREATE TABLE DOJANS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    DAYS VARCHAR(255),
    HOURS VARCHAR(255),
    QUOTE VARCHAR(255),
    SABOM VARCHAR(255),
    RESTRICTION VARCHAR(255)
);