INSERT INTO TOURNAMENTS (
    NAME,
    DATE,
    HOURS,
    ADDRESS,
    COST,
    IND_TUL,
    IND_FIGHT,
    IND_ROTURA_HABILIDAD,
    IND_ROTURA_POTENCIA,
    TEAM_TUL,
    TEAM_FIGHT,
    TEAM_DEFENSA_PERSONAL,
    TEAM_TUL_APLICADO,
    CAT_INFANTILES,
    CAT_CADETES_11_13,
    CAT_JUVENIL_14_17,
    CAT_ADULTO_18_34,
    CAT_VETERANO_PLATA_35_44,
    CAT_VETERANO_ORO_45,
    AFICHE
) VALUES (
    'Apertura Córdoba',
    '25/09/2024',
    '10:00',
    'Maestro Vidal 355',
    '1500',
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    'http://imagen.jpg'
);